### ISSUE TITLE
Compiler issue in Unity 5.4.0f3-HTP

### ISSUE THREAD

**Issue by gordonpagan** [awsdocs/aws-unity-developer-guide#1]
I was following the Step 1 of the step by step guide in trying to run the S3 example (AWSSDK.S3) and I got a fatal error in Unity regarding 

`streamReader.Close();`

which is line 259 0f S3Example.cs.

``
![image](https://cloud.githubusercontent.com/assets/2780623/23328941/448e60b4-fb25-11e6-8e26-7e9d4fa14480.png)

Of course this compiles up in VS15 ok but not in Unity which has an earlier version of the C# (4.4?). If use this vesion of Unity (5.4.0f3-HTP) because I am doing HoloLens development and find this is still the most stable version.

**Comment by gordonpagan** [comment]
If I alter:-

`streamReader.Close();`

to

`streamReader,Flush();`

which, in this case must flush the buffer after saving it but without closing it, the process gets a bit further and then we get the following error:-

![image](https://cloud.githubusercontent.com/assets/2780623/23329028/19002660-fb27-11e6-9f0d-c043b6fc9c11.png)

When you try to proceed to use VS15, the App folder is blank so  there is no project you can use. Please be aware that I am using a Windows Store solution here for it to be HoloLens compatible.

**Comment by ebattalio** [comment]
Closing. If this is still an issue in the newest Visual Studio, please open/reopen and add additional details.
