### ISSUE TITLE
Update zip file with newer dlls with more current version please

### ISSUE THREAD

**Issue by legut2** [awsdocs/aws-unity-developer-guide#4]
The zip file included with the "What is the AWS Mobile SDK for Unity?" documentation gives outdated files for the sdk. The files supplied work only up until Unity 2019.1. This can be seen in the following issue:
[github issue](https://github.com/aws/aws-sdk-net/issues/1286)

Could you please update this documentation to include a more current set of files for the SDK?
This will help prevent many developers from having to compile from source to use a newer version of unity. Newer versions of unity are necessary for using debugging tools such as Android logcat. Which conveniently is available in Unity 2019.1 and newer.
[Post explaining current process developers go through because of outdated files](https://lhkmarcus.com/2020/04/05/how-to-use-aws-sdk-in-unity-2019/)

There is even some mention of this problem at the following blog post:
https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/

**Comment by awsdan** [comment]
The AWS Mobile SDK for Unity is now included in the .NET SDK. For more information, see [what-is-unity-pluging.md](https://github.com/awsdocs/aws-unity-developer-guide/blob/main/doc_source/what-is-unity-plugin.md). The previous version of the standalone SDK is now archived, and is made available for reference purposes.
